-- CreateTable: provider_payments
-- This table tracks monthly payments to guides and influencers for their services and sessions
-- Providers earn 90% of revenue, platform keeps 10% as commission

CREATE TABLE IF NOT EXISTS "provider_payments" (
    "id" SERIAL PRIMARY KEY,
    "provider_id" INTEGER NOT NULL,
    "month" INTEGER NOT NULL CHECK (month >= 1 AND month <= 12),
    "year" INTEGER NOT NULL CHECK (year >= 2020),
    "total_revenue" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "platform_fee" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "provider_earnings" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "services_revenue" DECIMAL(10,2) DEFAULT 0,
    "services_count" INTEGER DEFAULT 0,
    "sessions_revenue" DECIMAL(10,2) DEFAULT 0,
    "sessions_count" INTEGER DEFAULT 0,
    "payment_status" VARCHAR(50) NOT NULL DEFAULT 'pending',
    "payment_method" VARCHAR(50),
    "transaction_id" VARCHAR(255),
    "payment_date" TIMESTAMP(6),
    "notes" TEXT,
    "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT "fk_provider_payments_provider" 
        FOREIGN KEY ("provider_id") 
        REFERENCES "users"("id") 
        ON DELETE CASCADE 
        ON UPDATE NO ACTION,
    
    CONSTRAINT "unique_provider_month_year" 
        UNIQUE("provider_id", "month", "year")
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS "idx_provider_payments_provider_id" ON "provider_payments"("provider_id");
CREATE INDEX IF NOT EXISTS "idx_provider_payments_month_year" ON "provider_payments"("month", "year");
CREATE INDEX IF NOT EXISTS "idx_provider_payments_status" ON "provider_payments"("payment_status");
CREATE INDEX IF NOT EXISTS "idx_provider_payments_created_at" ON "provider_payments"("created_at");
CREATE INDEX IF NOT EXISTS "idx_provider_payments_payment_date" ON "provider_payments"("payment_date");

-- Add comment to the table
COMMENT ON TABLE "provider_payments" IS 'Monthly payment records for guides and influencers (90% revenue share model)';
COMMENT ON COLUMN "provider_payments"."provider_id" IS 'Reference to users table (guide or influencer)';
COMMENT ON COLUMN "provider_payments"."month" IS 'Payment month (1-12)';
COMMENT ON COLUMN "provider_payments"."year" IS 'Payment year';
COMMENT ON COLUMN "provider_payments"."total_revenue" IS 'Total revenue generated by provider';
COMMENT ON COLUMN "provider_payments"."platform_fee" IS '10% platform commission';
COMMENT ON COLUMN "provider_payments"."provider_earnings" IS '90% provider earnings';
COMMENT ON COLUMN "provider_payments"."payment_status" IS 'pending, processing, paid, failed';
